# Generated by Django 5.0.6 on 2024-06-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourenrollmentsystem', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='program',
            field=models.CharField(default='default_program_value', max_length=55),
        ),
    ]
